table Products
	lineageTag: 4963b255-25ef-4ad6-8fc0-3991443146a0

	measure '# Products' = ```
			
			distinctcount( 'orders'[product name] ) 
			```
		formatString: #,##0
		displayFolder: Measures
		lineageTag: 1fb6f2e9-ed3c-4c97-8fdc-95d1d037a0de

	column 'Sub Brand Name'
		dataType: string
		lineageTag: 46b52e9b-f065-4a4b-a860-cbd239180893
		summarizeBy: none
		sourceColumn: Sub Brand Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ship Class for Part'
		dataType: string
		lineageTag: 8b05870e-ec7e-4bee-b9cc-3998508fd4c9
		summarizeBy: none
		sourceColumn: Ship Class for Part

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 31fc2387-5a7f-4655-a5ea-0bc51c07852a
		summarizeBy: none
		sourceColumn: Product Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Part Fit Grading'
		dataType: string
		lineageTag: 5832f019-fb01-4e09-ab32-ca411cb31e53
		summarizeBy: none
		sourceColumn: Part Fit Grading

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Key'
		dataType: int64
		lineageTag: 0af3eedf-9023-45c6-9b52-df7c4c69ee12
		summarizeBy: none
		sourceColumn: Product Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Subtype'
		dataType: string
		lineageTag: 15258ae0-314c-4258-b6a9-c5f4b1f7c0df
		summarizeBy: none
		sourceColumn: Product Subtype

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Type'
		dataType: string
		lineageTag: 85080b98-1526-4199-8045-b27395dcead7
		summarizeBy: none
		sourceColumn: Product Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MK
		dataType: string
		lineageTag: 434ef8cd-463c-423c-98d0-133def571872
		summarizeBy: none
		sourceColumn: MK

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: d09831f4-99c0-40cd-b760-3fde292b3c21
		summarizeBy: none
		sourceColumn: Color

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Production Series'
		dataType: string
		lineageTag: 2c8917a4-56c0-41b2-aea6-2b4db37b3711
		summarizeBy: none
		sourceColumn: Production Series

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Nameplate
		dataType: string
		lineageTag: 4e1f18fb-66c0-457f-a7df-65694bfe81de
		summarizeBy: none
		sourceColumn: Nameplate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Part
		dataType: string
		lineageTag: a78bca4e-9fc2-42b7-8e38-44a2800b9ad1
		summarizeBy: none
		sourceColumn: Part

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Maximum Temperature (K)'
		dataType: int64
		lineageTag: 2005d462-c934-4b0d-9746-b46329fb408d
		summarizeBy: sum
		sourceColumn: Maximum Temperature (K)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Business Line Leader'
		dataType: string
		lineageTag: f7d90ab0-1767-4d3d-884b-33ce7aab8421
		summarizeBy: none
		sourceColumn: Product Business Line Leader

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Tolerance (g)'
		dataType: int64
		lineageTag: 5b9d9f23-63fd-4aca-99c3-8c2952190f4c
		summarizeBy: sum
		sourceColumn: Tolerance (g)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Velocity Tolerance (Meters / Second)'
		dataType: int64
		lineageTag: 762198d6-0454-4be8-bd34-93a179964871
		summarizeBy: sum
		sourceColumn: Velocity Tolerance (Meters / Second)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Weight (Tonnes)'
		dataType: double
		lineageTag: cc3bfcfb-ca3a-48ef-a567-b767efcdf6bd
		summarizeBy: sum
		sourceColumn: Weight (Tonnes)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Flagship
		dataType: string
		lineageTag: 90c35094-c43c-4356-a89c-22a0af454731
		summarizeBy: none
		sourceColumn: Flagship

		annotation SummarizationSetBy = Automatic

	column 'Brand Class'
		dataType: string
		lineageTag: b17f5ebf-4180-4c3b-9a26-3aeb113994aa
		summarizeBy: none
		sourceColumn: Brand Class

		annotation SummarizationSetBy = Automatic

	column 'Brand Type'
		dataType: string
		lineageTag: f7c8483a-9232-42cb-a971-607d54d47ca2
		summarizeBy: none
		sourceColumn: Brand Type

		annotation SummarizationSetBy = Automatic

	column 'Brand Name'
		dataType: string
		lineageTag: d272db20-c8e9-4818-affa-22ca49bc7cdc
		summarizeBy: none
		sourceColumn: Brand Name

		annotation SummarizationSetBy = Automatic

	column 'Brand VP'
		dataType: string
		lineageTag: 3c23469f-16f4-4218-8e55-4a356c12bcfc
		summarizeBy: none
		sourceColumn: Brand VP

		annotation SummarizationSetBy = Automatic

	hierarchy 'Product Hierarchy'
		lineageTag: be3e77c0-e9ee-4ef7-947d-d4d075eeee9a

		level 'Product Type'
			lineageTag: 5dc23be4-9e7d-4d9c-9125-29fff24963af
			column: 'Product Type'

		level 'Product Subtype'
			lineageTag: aad230ae-d02b-40ca-909f-912eb59dbd84
			column: 'Product Subtype'

		level 'Product Name'
			lineageTag: 2faa8a87-f034-4a37-ae57-78226ae641ee
			column: 'Product Name'

		level Part
			lineageTag: 3f546d11-2759-4b51-bd76-87db29036a7b
			column: Part

		changedProperty = IsHidden

	partition Products = m
		mode: import
		queryGroup: Tables
		source =
				let
				    Source = Sql.Database("te3-training-eu.database.windows.net","SpacePartsCoDW"),
				    Data = Source{[Schema="Dimview",Item="Products"]}[Data],
				    #"Merged Queries" = Table.FuzzyNestedJoin(Data, {"Sub Brand Name"}, Brands1234, {"Sub Brand"}, "Brands", JoinKind.FullOuter, [IgnoreCase=true, IgnoreSpace=true]),
				    #"Expanded Brands" = Table.ExpandTableColumn(#"Merged Queries", "Brands", {"Flagship", "Class", "Type", "Brand", "Product Brand VP"}, {"Flagship", "Class", "Type.1", "Brand", "Product Brand VP"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Brands",{{"Class", "Brand Class"}, {"Type.1", "Brand Type"}, {"Brand", "Brand Name"}, {"Product Brand VP", "Brand VP"}, {"Subtype", "Product Subtype"}, {"Type", "Product Type"}, {"Material", "Part"}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Renamed Columns", each [Product Key] > 0),
				    #"Filtered Rows" = Table.SelectRows(#"Filtered Rows1", each [Product Subtype] = "Bio-Ray" or [Product Subtype] = "Emr" or [Product Subtype] = "Ionic Lasers" or [Product Subtype] = "Pdc" or [Product Subtype] = "Plasma Lasers" or [Product Subtype] = "Proximity" or [Product Subtype] = "Rail" or [Product Subtype] = "Torpedo" or [Product Subtype] = "Shielding Systems")
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

