name: Power BI CI

on:
  workflow_dispatch:

jobs:
  build_datasets:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Tabular Editor and Default Rules
        shell: pwsh
        run: |
          $path = "${{ github.workspace }}"
          $tempPath = "$path\_temp"
          $toolPath = "$path\_tools\TE"
          New-Item -ItemType Directory -Path $tempPath -ErrorAction SilentlyContinue | Out-Null              

          Write-Host "Downloading Tabular Editor binaries"
          $downloadUrl = "https://github.com/TabularEditor/TabularEditor/releases/latest/download/TabularEditor.Portable.zip"
          $zipFile = "$tempPath\TabularEditor.zip"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $zipFile
          Expand-Archive -Path $zipFile -DestinationPath $toolPath -Force            

          Write-Host "Downloading Dataset default rules"
          $downloadUrl = "https://github.com/microsoft/Analysis-Services/raw/master/BestPracticeRules/Japanese/BPARules.json"
          Invoke-WebRequest -Uri $downloadUrl -OutFile "$tempPath\Rules-Dataset.json"

      - name: Run Dataset Rules
        shell: pwsh
        run: |
          $path = "${{ github.workspace }}"
          $tempPath = "$path\_temp"
          $toolPath = "$path\_tools\TE\TabularEditor.exe"
          $rulesPath = "$path\Rules-Dataset.json"
          $violationFile = "$path\violations.txt"

          if (!(Test-Path $rulesPath))
          {
              Write-Host "Running downloaded rules"
              $rulesPath = "$tempPath\Rules-Dataset.json"
          }

          # 違反項目を保存するためのファイルを初期化
          New-Item -Path $violationFile -ItemType File -Force | Out-Null

          $itemsFolders = Get-ChildItem -Path $path -recurse -include ("*.pbidataset", "*.pbism")

          foreach($itemFolder in $itemsFolders)
          {   
              $itemPath = "$($itemFolder.Directory.FullName)\definition"

              if (!(Test-Path $itemPath))
              {
                  $itemPath = "$($itemFolder.Directory.FullName)\model.bim"

                  if (!(Test-Path $itemPath))
                  {
                      throw "Cannot find semantic model definition."
                  }
              }

              Write-Host "Running rules for: '$itemPath'"

              # Tabular Editorを実行してルール違反をチェック
              Start-Process -FilePath "$toolPath" -ArgumentList """$itemPath"" -A ""$rulesPath"" -V" -NoNewWindow -Wait -PassThru | Out-File -Append -FilePath $violationFile
          }

          # 違反項目をコンソールに表示
          Get-Content $violationFile

      - name: Upload Violations
        uses: actions/upload-artifact@v4
        with:
          name: dataset-violations
          path: violations.txt

  build_reports:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download PBIXInspector
        shell: pwsh
        run: |
          $path = "${{ github.workspace }}"
          $tempPath = "$path\_temp"
          $toolPath = "$path\_Tools\PBIInspector"
          New-Item -ItemType Directory -Path $tempPath -ErrorAction SilentlyContinue | Out-Null

          Write-Host "Downloading PBI Inspector"
          $downloadUrl = "https://github.com/NatVanG/PBI-Inspector/releases/latest/download/win-x64-CLI.zip" 
          $zipFile = "$tempPath\PBIXInspector.zip"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $zipFile
          Expand-Archive -Path $zipFile -DestinationPath $toolPath -Force                            

          Write-Host "Downloading Report default rules"
          $downloadUrl = "https://raw.githubusercontent.com/NatVanG/PBI-Inspector/main/Rules/Base-rules.json"
          Invoke-WebRequest -Uri $downloadUrl -OutFile "$tempPath\Rules-Report.json"

      - name: Run Report Rules
        shell: pwsh
        run: |
          $path = "${{ github.workspace }}"
          $tempPath = "$path\_temp"
          $toolPath = "$path\_Tools\PBIInspector\win-x64\CLI\PBIXInspectorCLI.exe"
          $rulesPath = "$path\Rules-Report.json"
          $violationFile = "$path\report-violations.txt"

          if (!(Test-Path $rulesPath))
          {
              Write-Host "Running default downloaded rules"
              $rulesPath = "$tempPath\Rules-Report.json"
          }

          # 違反項目を保存するためのファイルを初期化
          New-Item -Path $violationFile -ItemType File -Force | Out-Null

          $itemsFolders = Get-ChildItem -Path $path -recurse -include *.pbir

          foreach($itemFolder in $itemsFolders)
          {   
              $itemPath = $itemFolder.Directory.FullName
              
              Write-Host "Running rules for: '$itemPath'"

              # PBI Inspectorを実行してルール違反をチェック
              Start-Process -FilePath "$toolPath" -ArgumentList "-pbipreport ""$itemPath"" -rules ""$rulesPath"" -formats ""ADO""" -NoNewWindow -Wait -PassThru | Out-File -Append -FilePath $violationFile
          }

          # 違反項目をコンソールに表示
          Get-Content $violationFile

      - name: Upload Violations
        uses: actions/upload-artifact@v4
        with:
          name: report-violations
          path: report-violations.txt
